//! LLM conversation message types.

use serde::{Deserialize, Serialize};

/// Generate a fresh server-assigned message ID.
///
/// Used as the serde default for `Message::msg_id` so that messages persisted
/// before this field existed are stamped with a stable UUID on first load.
/// New messages built via `Message::user`, `Message::assistant`, etc. also
/// receive a fresh server-generated UUID rather than trusting any
/// LLM-provided identifier (which can collide across sessions or be reused).
fn new_msg_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// A message in an LLM conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Server-assigned unique message ID (UUID v4).
    ///
    /// Always generated by OpenFang at message creation time. LLM providers'
    /// own `id` fields are unreliable (different formats per provider, can
    /// collide across sessions, sometimes absent), so we never use them as the
    /// primary key. The provider-supplied ID, when present, is preserved in
    /// `provider_msg_id` for debugging only.
    ///
    /// Old sessions on disk that predate this field will deserialize with a
    /// freshly-generated UUID — they had no stable ID before, so this is a
    /// strict improvement.
    #[serde(default = "new_msg_id")]
    pub msg_id: String,
    /// Optional LLM-provided message identifier (e.g. Anthropic `msg_abc...`,
    /// OpenAI `chatcmpl-...`). Preserved for debugging/correlation only —
    /// never used as the primary identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_msg_id: Option<String>,
    /// The role of the sender.
    pub role: Role,
    /// The content of the message.
    pub content: MessageContent,
}

/// The role of a message sender in an LLM conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System prompt.
    System,
    /// Human user.
    #[default]
    User,
    /// AI assistant.
    Assistant,
}

/// Content of a message — can be simple text or structured blocks.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    /// Simple text content.
    Text(String),
    /// Structured content blocks.
    Blocks(Vec<ContentBlock>),
}

impl Default for MessageContent {
    fn default() -> Self {
        MessageContent::Text(String::new())
    }
}

impl Default for Message {
    fn default() -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::User,
            content: MessageContent::Text(String::new()),
        }
    }
}

/// A content block within a message.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ContentBlock {
    /// A text block.
    #[serde(rename = "text")]
    Text {
        /// The text content.
        text: String,
        /// Provider-specific metadata (e.g. Gemini `thoughtSignature`).
        /// Opaque to the core — drivers read/write this to round-trip
        /// fields the provider requires on subsequent requests.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<serde_json::Value>,
    },
    /// An inline base64-encoded image.
    #[serde(rename = "image")]
    Image {
        /// MIME type (e.g. "image/png", "image/jpeg").
        media_type: String,
        /// Base64-encoded image data.
        data: String,
    },
    /// A tool use request from the assistant.
    #[serde(rename = "tool_use")]
    ToolUse {
        /// Unique ID for this tool use.
        id: String,
        /// The tool name.
        name: String,
        /// The tool input parameters.
        input: serde_json::Value,
        /// Provider-specific metadata (e.g. Gemini `thoughtSignature`).
        /// Opaque to the core — drivers read/write this to round-trip
        /// fields the provider requires on subsequent requests.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<serde_json::Value>,
    },
    /// A tool result from executing a tool.
    #[serde(rename = "tool_result")]
    ToolResult {
        /// The tool_use ID this result corresponds to.
        tool_use_id: String,
        /// The tool name (for Gemini FunctionResponse). Empty for legacy sessions.
        #[serde(default)]
        tool_name: String,
        /// The result content.
        content: String,
        /// Whether the tool execution errored.
        is_error: bool,
    },
    /// Extended thinking content block (model's reasoning trace).
    ///
    /// Preserved across turns so reasoning models retain state. Anthropic's
    /// extended thinking requires the `signature` to be echoed on resubmission;
    /// other providers (Gemini thought signatures, DeepSeek/Qwen
    /// `reasoning_content`, MiniMax inline `<think>`) round-trip via
    /// `provider_metadata` or by inlining into the assistant message body.
    #[serde(rename = "thinking")]
    Thinking {
        /// The thinking/reasoning text.
        thinking: String,
        /// Provider-issued signature required to resubmit thinking blocks
        /// (Anthropic extended thinking). `None` for providers that don't
        /// emit a signature.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
        /// Provider-specific metadata (e.g. `{"format": "reasoning_content"}`
        /// or `{"format": "inline_think"}` so the outbound driver knows how
        /// the upstream model originally delivered the reasoning).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        provider_metadata: Option<serde_json::Value>,
    },
    /// Anthropic redacted-thinking block — encrypted reasoning the model
    /// chose to hide. The `data` blob is opaque to us but MUST be echoed
    /// verbatim on subsequent turns, otherwise Anthropic rejects the
    /// resubmitted history. Only emitted by the Anthropic driver.
    #[serde(rename = "redacted_thinking")]
    RedactedThinking {
        /// Opaque encrypted reasoning payload from Anthropic.
        data: String,
    },
    /// Catch-all for unrecognized content block types (forward compatibility).
    #[serde(other)]
    Unknown,
}

/// Allowed image media types.
const ALLOWED_IMAGE_TYPES: &[&str] = &["image/png", "image/jpeg", "image/gif", "image/webp"];

/// Maximum decoded image size (5 MB).
const MAX_IMAGE_BYTES: usize = 5 * 1024 * 1024;

/// Validate an image content block.
///
/// Checks that the media type is an allowed image format and the
/// base64 data doesn't exceed 5 MB when decoded (~7 MB base64).
pub fn validate_image(media_type: &str, data: &str) -> Result<(), String> {
    if !ALLOWED_IMAGE_TYPES.contains(&media_type) {
        return Err(format!(
            "Unsupported image type '{}'. Allowed: {}",
            media_type,
            ALLOWED_IMAGE_TYPES.join(", ")
        ));
    }
    // Base64 encodes 3 bytes into 4 chars, so max base64 len ≈ MAX_IMAGE_BYTES * 4/3
    let max_b64_len = MAX_IMAGE_BYTES * 4 / 3 + 4; // small padding allowance
    if data.len() > max_b64_len {
        return Err(format!(
            "Image too large: {} bytes base64 (max ~{} bytes for {} MB decoded)",
            data.len(),
            max_b64_len,
            MAX_IMAGE_BYTES / (1024 * 1024)
        ));
    }
    Ok(())
}

impl MessageContent {
    /// Create simple text content.
    pub fn text(content: impl Into<String>) -> Self {
        MessageContent::Text(content.into())
    }

    /// Get the total character length of text in this content.
    pub fn text_length(&self) -> usize {
        match self {
            MessageContent::Text(s) => s.len(),
            MessageContent::Blocks(blocks) => blocks
                .iter()
                .map(|b| match b {
                    ContentBlock::Text { text, .. } => text.len(),
                    ContentBlock::ToolResult { content, .. } => content.len(),
                    ContentBlock::Thinking { thinking, .. } => thinking.len(),
                    ContentBlock::ToolUse { name, input, .. } => {
                        name.len() + input.to_string().len()
                    }
                    ContentBlock::Image { .. }
                    | ContentBlock::RedactedThinking { .. }
                    | ContentBlock::Unknown => 0,
                })
                .sum(),
        }
    }

    /// Extract all text content as a single string.
    pub fn text_content(&self) -> String {
        match self {
            MessageContent::Text(s) => s.clone(),
            MessageContent::Blocks(blocks) => blocks
                .iter()
                .filter_map(|b| match b {
                    ContentBlock::Text { text, .. } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join(""),
        }
    }
}

impl Message {
    /// Create a system message.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::System,
            content: MessageContent::Text(content.into()),
        }
    }

    /// Create a user message.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::User,
            content: MessageContent::Text(content.into()),
        }
    }

    /// Create a user message with structured content blocks (e.g. text + images).
    pub fn user_with_blocks(blocks: Vec<ContentBlock>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::User,
            content: MessageContent::Blocks(blocks),
        }
    }

    /// Create an assistant message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::Assistant,
            content: MessageContent::Text(content.into()),
        }
    }

    /// Create an assistant message with structured content blocks.
    ///
    /// Used to preserve `Thinking` blocks (with signatures and reasoning text)
    /// across persistence so reasoning models retain state between turns.
    pub fn assistant_with_blocks(blocks: Vec<ContentBlock>) -> Self {
        Self {
            msg_id: new_msg_id(),
            provider_msg_id: None,
            role: Role::Assistant,
            content: MessageContent::Blocks(blocks),
        }
    }

    /// Attach a provider-supplied message ID (for debugging only).
    ///
    /// The server-generated `msg_id` remains the primary identifier — this
    /// records what the upstream LLM called the same message so we can
    /// correlate logs/traces with provider dashboards.
    pub fn with_provider_msg_id(mut self, provider_id: impl Into<String>) -> Self {
        self.provider_msg_id = Some(provider_id.into());
        self
    }
}

/// Why the LLM stopped generating.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model finished its turn.
    EndTurn,
    /// The model wants to use a tool.
    ToolUse,
    /// The model hit the token limit.
    MaxTokens,
    /// The model hit a stop sequence.
    StopSequence,
}

/// Token usage information from an LLM call.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens used for the input/prompt.
    pub input_tokens: u64,
    /// Tokens generated in the output.
    pub output_tokens: u64,
    /// Tokens served from the provider's prompt cache (0 when unsupported).
    #[serde(default)]
    pub cached_tokens: u64,
}

impl TokenUsage {
    /// Total tokens used.
    pub fn total(&self) -> u64 {
        self.input_tokens + self.output_tokens
    }
}

/// Reply directives extracted from agent output.
///
/// These control how the response is delivered back to the user/channel:
/// - `reply_to`: reply to a specific message ID
/// - `current_thread`: reply in the current thread
/// - `silent`: suppress the response entirely
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ReplyDirectives {
    /// Reply to a specific message ID.
    pub reply_to: Option<String>,
    /// Reply in the current thread.
    pub current_thread: bool,
    /// Suppress the response from being sent.
    pub silent: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_creation() {
        let msg = Message::user("Hello");
        assert_eq!(msg.role, Role::User);
        match msg.content {
            MessageContent::Text(text) => assert_eq!(text, "Hello"),
            _ => panic!("Expected text content"),
        }
    }

    #[test]
    fn test_token_usage() {
        let usage = TokenUsage {
            input_tokens: 100,
            output_tokens: 50,
        };
        assert_eq!(usage.total(), 150);
    }

    #[test]
    fn test_validate_image_valid() {
        assert!(validate_image("image/png", "iVBORw0KGgo=").is_ok());
        assert!(validate_image("image/jpeg", "data").is_ok());
        assert!(validate_image("image/gif", "data").is_ok());
        assert!(validate_image("image/webp", "data").is_ok());
    }

    #[test]
    fn test_validate_image_bad_type() {
        let err = validate_image("image/svg+xml", "data").unwrap_err();
        assert!(err.contains("Unsupported image type"));
        let err = validate_image("text/plain", "data").unwrap_err();
        assert!(err.contains("Unsupported image type"));
    }

    #[test]
    fn test_validate_image_too_large() {
        let huge = "A".repeat(8_000_000); // ~6MB base64
        let err = validate_image("image/png", &huge).unwrap_err();
        assert!(err.contains("too large"));
    }

    #[test]
    fn test_content_block_image_serde() {
        let block = ContentBlock::Image {
            media_type: "image/png".to_string(),
            data: "base64data".to_string(),
        };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(json["type"], "image");
        assert_eq!(json["media_type"], "image/png");
    }

    #[test]
    fn test_content_block_unknown_deser() {
        let json = serde_json::json!({"type": "future_block_type"});
        let block: ContentBlock = serde_json::from_value(json).unwrap();
        assert!(matches!(block, ContentBlock::Unknown));
    }

    #[test]
    fn test_thinking_block_roundtrip_preserves_signature() {
        // Anthropic extended thinking — the signature MUST round-trip through
        // serde so it can be echoed on the next request.
        let block = ContentBlock::Thinking {
            thinking: "Let me reason about this carefully...".to_string(),
            signature: Some("sig_abc123_anthropic_extended_thinking".to_string()),
            provider_metadata: None,
        };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(json["type"], "thinking");
        assert_eq!(json["signature"], "sig_abc123_anthropic_extended_thinking");

        // Round-trip through serialize → deserialize (e.g. SQLite session blob)
        let serialized = serde_json::to_string(&block).unwrap();
        let restored: ContentBlock = serde_json::from_str(&serialized).unwrap();
        match restored {
            ContentBlock::Thinking {
                thinking,
                signature,
                ..
            } => {
                assert_eq!(thinking, "Let me reason about this carefully...");
                assert_eq!(
                    signature.as_deref(),
                    Some("sig_abc123_anthropic_extended_thinking")
                );
            }
            _ => panic!("expected Thinking block"),
        }
    }

    #[test]
    fn test_thinking_block_roundtrip_with_provider_metadata() {
        // OpenAI-compat models (DeepSeek-R1, Qwen3, MiniMax) — record the
        // wire format so the outbound driver knows whether to re-emit as
        // `reasoning_content` or inline `<think>` tags.
        let block = ContentBlock::Thinking {
            thinking: "step-by-step analysis".to_string(),
            signature: None,
            provider_metadata: Some(serde_json::json!({"format": "inline_think"})),
        };
        let serialized = serde_json::to_string(&block).unwrap();
        let restored: ContentBlock = serde_json::from_str(&serialized).unwrap();
        match restored {
            ContentBlock::Thinking {
                thinking,
                signature,
                provider_metadata,
            } => {
                assert_eq!(thinking, "step-by-step analysis");
                assert!(signature.is_none());
                let meta = provider_metadata.expect("provider_metadata preserved");
                assert_eq!(meta["format"], "inline_think");
            }
            _ => panic!("expected Thinking block"),
        }
    }

    #[test]
    fn test_thinking_block_legacy_deser() {
        // Existing sessions on disk only have `{"type": "thinking", "thinking": "..."}`.
        // The new fields must be optional so old payloads still load.
        let json = serde_json::json!({"type": "thinking", "thinking": "old session reasoning"});
        let block: ContentBlock = serde_json::from_value(json).unwrap();
        match block {
            ContentBlock::Thinking {
                thinking,
                signature,
                provider_metadata,
            } => {
                assert_eq!(thinking, "old session reasoning");
                assert!(signature.is_none());
                assert!(provider_metadata.is_none());
            }
            _ => panic!("expected Thinking block"),
        }
    }

    #[test]
    fn test_assistant_with_blocks_preserves_thinking() {
        // A complete round-trip: build an assistant turn that mixes Thinking +
        // Text (the shape we'll store after fix) and confirm the Thinking
        // block survives serialization (msgpack is what session.rs uses; JSON
        // exercises the same serde path).
        let msg = Message::assistant_with_blocks(vec![
            ContentBlock::Thinking {
                thinking: "Internal reasoning".to_string(),
                signature: Some("sig_xyz".to_string()),
                provider_metadata: None,
            },
            ContentBlock::Text {
                text: "Hello!".to_string(),
                provider_metadata: None,
            },
        ]);
        let bytes = rmp_serde::to_vec_named(&msg).expect("msgpack encode");
        let restored: Message = rmp_serde::from_slice(&bytes).expect("msgpack decode");
        match restored.content {
            MessageContent::Blocks(blocks) => {
                assert_eq!(blocks.len(), 2);
                match &blocks[0] {
                    ContentBlock::Thinking {
                        thinking,
                        signature,
                        ..
                    } => {
                        assert_eq!(thinking, "Internal reasoning");
                        assert_eq!(signature.as_deref(), Some("sig_xyz"));
                    }
                    _ => panic!("expected Thinking first"),
                }
            }
            _ => panic!("expected Blocks content"),
        }
    }

    #[test]
    fn test_msg_id_is_server_assigned_uuid() {
        // Every constructor must stamp a server-side UUID — never trust the
        // LLM-provided ID as the primary key.
        let a = Message::user("hello");
        let b = Message::user("hello");
        assert_ne!(a.msg_id, b.msg_id, "msg_id must be unique per message");
        // Must parse as a valid UUID v4.
        let parsed = uuid::Uuid::parse_str(&a.msg_id).expect("msg_id must be a valid UUID");
        assert_eq!(parsed.get_version_num(), 4, "msg_id must be UUID v4");
        // Provider id defaults to None.
        assert!(a.provider_msg_id.is_none());
    }

    #[test]
    fn test_provider_msg_id_is_recorded_but_not_primary() {
        // The LLM-supplied identifier is preserved for debugging only — the
        // server-generated `msg_id` is unchanged and remains the primary key.
        let msg = Message::assistant("hi").with_provider_msg_id("msg_abc123_anthropic_collidable");
        assert_eq!(
            msg.provider_msg_id.as_deref(),
            Some("msg_abc123_anthropic_collidable")
        );
        // msg_id is still the server UUID, NOT the provider string.
        assert_ne!(msg.msg_id, "msg_abc123_anthropic_collidable");
        assert!(uuid::Uuid::parse_str(&msg.msg_id).is_ok());
    }

    #[test]
    fn test_legacy_message_deser_gets_fresh_msg_id() {
        // Sessions persisted before this field existed must still load — the
        // serde default stamps a fresh UUID so callers always see a stable ID.
        let legacy = serde_json::json!({
            "role": "user",
            "content": "old session message"
        });
        let restored: Message = serde_json::from_value(legacy).unwrap();
        assert!(
            uuid::Uuid::parse_str(&restored.msg_id).is_ok(),
            "legacy payloads must deserialize with a server-stamped UUID"
        );
        assert!(restored.provider_msg_id.is_none());
    }

    #[test]
    fn test_msg_id_survives_msgpack_roundtrip() {
        // SessionStore persists via rmp_serde — make sure msg_id round-trips.
        let original = Message::user("hello").with_provider_msg_id("msg_xyz");
        let bytes = rmp_serde::to_vec_named(&original).expect("encode");
        let restored: Message = rmp_serde::from_slice(&bytes).expect("decode");
        assert_eq!(restored.msg_id, original.msg_id);
        assert_eq!(restored.provider_msg_id.as_deref(), Some("msg_xyz"));
    }

    #[test]
    fn test_user_with_blocks() {
        let blocks = vec![
            ContentBlock::Text {
                text: "What is in this image?".to_string(),
                provider_metadata: None,
            },
            ContentBlock::Image {
                media_type: "image/jpeg".to_string(),
                data: "base64data".to_string(),
            },
        ];
        let msg = Message::user_with_blocks(blocks);
        assert_eq!(msg.role, Role::User);
        match msg.content {
            MessageContent::Blocks(ref b) => {
                assert_eq!(b.len(), 2);
                assert!(
                    matches!(&b[0], ContentBlock::Text { text, .. } if text == "What is in this image?")
                );
                assert!(
                    matches!(&b[1], ContentBlock::Image { media_type, .. } if media_type == "image/jpeg")
                );
            }
            _ => panic!("Expected blocks content"),
        }
    }
}
